<a href="https://colab.research.google.com/github/OfomiMatthew/hamoye-ml-intro/blob/main/Machine_learning_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [8]:
# fetching and reading dataset
df = pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding="latin-1")
df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [35]:
#  getting data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [11]:
# getting shape of data
df.shape

(60943, 12)

In [12]:
#  getting rows and columns of data
df.iloc[:]

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [26]:
# description of different parameters on dataset
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [32]:
x_count = df['Area'].unique()
print(len(x_count))

49

In [34]:
y = [(2, 4), (7, 8), (1, 5, 9)]
x = y[1][1]
print(x)

8

In [39]:
madagascar_2015_data = df[(df['Area'] == 'Madagascar') & (df['Y2015'])]
madagascar_2015_data

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
30715,129,Madagascar,2501,Population,511,Total Population - Both sexes,1000 persons,23590.00,24234.00,24894.00,25571.00,26262.00
30717,129,Madagascar,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,1986.00,1922.00,1918.00,1943.00,1938.00
30718,129,Madagascar,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,44.45,43.26,43.35,43.94,44.17
30719,129,Madagascar,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,22.18,22.97,23.83,25.26,24.12
30720,129,Madagascar,2903,Vegetal Products,664,Food supply (kcal/capita/day),kcal/capita/day,1853.00,1788.00,1782.00,1808.00,1804.00
...,...,...,...,...,...,...,...,...,...,...,...,...
32147,129,Madagascar,2899,Miscellaneous,5301,Domestic supply quantity,1000 tonnes,10.00,11.00,11.00,11.00,12.00
32149,129,Madagascar,2899,Miscellaneous,5142,Food,1000 tonnes,10.00,11.00,11.00,11.00,12.00
32150,129,Madagascar,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,0.44,0.44,0.44,0.44,0.44
32152,129,Madagascar,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01
32153,129,Madagascar,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01

In [44]:
df['Y2014'].isnull().sum()

1589

In [48]:
grouped = df.groupby('Element').sum()
processing_2017_sum = grouped.loc['Processing', 'Y2017']
processing_2017_sum

292836.0

In [66]:
correlation = df['Element Code'].corr(df['Y2014'])
print(correlation)

0.024456819495221754

In [67]:
correlation = df['Element Code'].corr(df['Y2015'])
print(correlation)

0.023889199301639956

In [68]:
correlation = df['Element Code'].corr(df['Y2016'])
print(correlation)

0.023443997584961424

In [69]:
correlation = df['Element Code'].corr(df['Y2017'])
print(correlation)

0.02425400776004575

In [70]:
correlation = df['Element Code'].corr(df['Y2018'])
print(correlation)

0.02427857195351955